### ISSUE TITLE
Devnet api url has changed

### ISSUE THREAD

**Issue by gokaykucuk** [Gusarich/pysol#1]
Currently the library has the following,
```
CHAINS = {
    'mainnet': 'https://api.mainnet-beta.solana.com',
    'testnet': 'https://testnet.solana.com',
    'devnet': 'https://devnet.solana.com'
}
```
but if we navigate to devnet via browser,
`https://devnet.solana.com/ has been deprecated, please use https://api.devnet.solana.com/ instead`
is shown. So it needs to be updated.

Would you like me to create a PR?

**Comment by Gusarich** [comment]
Hello! Yes, feel free to create pull request.
Sorry for long response, I don't work on this library anymore, you can also fork it and continue adding new features or rewrite current code so it works without solana CLI
